# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HS Krishna Chaitanya
email: hskrishna29@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "hskrishn29.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  hskrishna29
repository: "hskrishna29/hskrishna29.github.io"
linkedin_url: "https://www.linkedin.com/in/hskrishna69/"
soundcloud_url: "https://soundcloud.com/hskc/tracks"
github_url: "https://github.com/hskrishna29"
youtube_url: "https://www.youtube.com/user/boozer47"

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
